import { createFileRoute } from "@tanstack/react-router";
import { useCallback, useEffect, useRef, useState } from "react";
import { motion, AnimatePresence } from "framer-motion";
import {
  Upload,
  FileText,
  Send,
  Loader2,
  X,
  Mic,
  Square,
  Scale,
  Sparkles,
  ShieldCheck,
  Copy,
  Check,
  FileDown,
  Volume2,
  BookOpen,
  ArrowRight,
  Gavel,
  Activity,
  History,
} from "lucide-react";
import { Navbar } from "@/components/Navbar";

export const Route = createFileRoute("/portal")({
  head: () => ({
    meta: [
      { title: "Consultation Portal — HaqAI" },
      {
        name: "description",
        content:
          "Submit your documents and case description to receive AI-powered legal guidance grounded in Pakistani law.",
      },
    ],
  }),
  component: Portal,
});

const translations = {
  en: {
    portalBadge: "Portal",
    title: "Consultation",
    desk: "Desk",
    subtitle: "Upload documents or describe your legal query. HaqAI analyzes case files, cross-references local statutes, and generates a structured legal opinion instantly.",
    caseSubmissions: "Case Submissions",
    liveAnalysisNode: "Live Analysis Node",
    attachFiles: "Attach Case Files / Documents",
    dragDrop: "Drag & Drop file or click to browse",
    fileTypes: "PDF, PNG, JPG (FIRs, Pleadings, Registry Deeds, Eviction Notices)",
    provideFacts: "Provide Facts / Context",
    placeholderText: "Describe the events, parties involved, and the specific assistance you require...",
    voiceAnnotationActive: "Voice annotation active",
    voiceAnnotationInactive: "Voice annotation inactive",
    micError: "Voice recording isn't supported in this browser.",
    micDenied: "Microphone access was denied. Allow access to record a voice message.",
    submitBtn: "Analyze Under Pakistani Law",
    submitLoading: "Processing File & Data...",
    encryptionAlert: "Symmetric encryption. Transcripts are audited inside private servers.",
    briefTitle: "Legal Guidance Brief",
    copyBtn: "Copy",
    copiedBtn: "Copied",
    dispatchTitle: "Legal Brief Dispatch",
    dispatchSubtitle: "Your counsel is sitting idle. Please submit documents or describe your case details in the input console to spin up the advisor pipeline.",
    waitingInputs: "Waiting on inputs",
    metricsTitle: "System Performance & Verification Metrics",
    retrievalAccuracy: "Retrieval Accuracy",
    vectorMatch: "Vector Cosine Match",
    processSpeed: "Process Speed",
    retrieval: "Retrieval",
    generation: "Gen",
    analysisFindings: "Legal Analysis & Findings",
    statutesPrecedents: "Local Statutes & Judgments References",
    noSources: "No direct local source document links cited in this response.",
    disclaimer: "This guidance is generated by HaqAI and is intended for informational orientation only — not a substitute for advice from a qualified legal practitioner.",
    audioNode: "AI Audio Processing Node"
  },
  ur: {
    portalBadge: "پورٹل",
    title: "مشاورتی",
    desk: "ڈیسک",
    subtitle: "دستاویزات اپ لوڈ کریں یا اپنے قانونی سوال کی وضاحت کریں۔ HaqAI کیس فائلوں کا تجزیہ کرتا ہے، مقامی قوانین کا موازنہ کرتا ہے، اور فوری طور پر ایک جامع قانونی رائے پیش کرتا ہے۔",
    caseSubmissions: "مقدمہ کی جمع آوری",
    liveAnalysisNode: "لائیو تجزیاتی نوڈ",
    attachFiles: "مقدمہ کی فائلیں / دستاویزات منسلک کریں",
    dragDrop: "فائل یہاں ڈریگ کریں یا براؤز کرنے کے لیے کلک کریں",
    fileTypes: "پی ڈی ایف، پی این جی، جے پی جی (ایف آئی آر، درخواستیں، رجسٹری ڈیڈز، نوٹس)",
    provideFacts: "حقائق / پس منظر فراہم کریں",
    placeholderText: "اپنا قانونی سوال لکھیں...",
    voiceAnnotationActive: "صوتی نوٹ فعال ہے",
    voiceAnnotationInactive: "صوتی نوٹ غیر فعال ہے",
    micError: "اس براؤزر میں آواز کی ریکارڈنگ سپورٹڈ نہیں ہے۔",
    micDenied: "مائیکروفون تک رسائی کی اجازت نہیں ملی۔ ریکارڈنگ کے لیے اجازت دیں۔",
    submitBtn: "پاکستانی قانون کے تحت تجزیہ کریں",
    submitLoading: "فائل اور ڈیٹا پروسیس ہو رہا ہے...",
    encryptionAlert: "ہمہ جہت انکرپشن۔ تمام معلومات نجی سرورز میں محفوظ ہیں۔",
    briefTitle: "قانونی رہنمائی کی تفصیل",
    copyBtn: "کاپی کریں",
    copiedBtn: "کاپی ہو گیا",
    dispatchTitle: "قانونی رہنمائی کا انتظار ہے",
    dispatchSubtitle: "آپ کا قانونی مشیر فی الحال فعال نہیں ہے۔ مشاورتی عمل شروع کرنے کے لیے براہ کرم معلومات یا دستاویزات فراہم کریں۔",
    waitingInputs: "ان پٹ کا انتظار ہے",
    metricsTitle: "سستم کی کارکردگی اور تصدیقی پیمائش",
    retrievalAccuracy: "معلومات کی درستگی",
    vectorMatch: "ویکٹر مماثلت",
    processSpeed: "پروسیسنگ کی رفتار",
    retrieval: "تلاش کا وقت",
    generation: "تخلیق کا وقت",
    analysisFindings: "قانونی تجزیہ اور نتائج",
    statutesPrecedents: "مقامی قوانین اور عدالتی فیصلوں کے حوالہ جات",
    noSources: "اس جواب میں براہ راست کوئی مقامی دستاویزی حوالہ نہیں ملا۔",
    disclaimer: "یہ رہنمائی HaqAI کے ذریعے تیار کی گئی ہے اور صرف معلوماتی مقاصد کے لیے ہے — کسی مستند وکیل کے مشورے کا متبادل نہیں ہے۔",
    audioNode: "صوتی پروسیسنگ نوڈ"
  }
};

function Portal() {
  const [file, setFile] = useState<File | null>(null);
  const [description, setDescription] = useState("");
  const [loading, setLoading] = useState(false);
  const [scanStep, setScanStep] = useState(0);
  const [copied, setCopied] = useState(false);
  const [language, setLanguage] = useState<"en" | "ur">("en");
  
  useEffect(() => {
    const savedLang = (localStorage.getItem("language") as "en" | "ur") || "en";
    setLanguage(savedLang);

    const handleLangChange = (e: Event) => {
      const customEvent = e as CustomEvent<"en" | "ur">;
      setLanguage(customEvent.detail || "en");
    };

    window.addEventListener("language-changed", handleLangChange);
    return () => {
      window.removeEventListener("language-changed", handleLangChange);
    };
  }, []);

  const [response, setResponse] = useState<{
    response: string;
    sources: { file: string; page: string }[];
    metrics: {
      retrieval_latency: number;
      generation_latency: number;
      total_latency: number;
      average_accuracy: number;
      scores: number[];
    };
  } | null>(null);

  const [dragOver, setDragOver] = useState(false);
  const fileInput = useRef<HTMLInputElement>(null);
  const recognitionRef = useRef<any>(null);
  const [audioBlob, setAudioBlob] = useState<Blob | null>(null);
  const [audioUrl, setAudioUrl] = useState<string | null>(null);
  const [isRecording, setIsRecording] = useState(false);
  const [recordingError, setRecordingError] = useState<string | null>(null);

  const [recordingSeconds, setRecordingSeconds] = useState(0);

  // Timer for voice recording
  useEffect(() => {
    let timer: any;
    if (isRecording) {
      setRecordingSeconds(0);
      timer = setInterval(() => {
        setRecordingSeconds((prev) => prev + 1);
      }, 1000);
    } else {
      setRecordingSeconds(0);
    }
    return () => clearInterval(timer);
  }, [isRecording]);

  const formatTime = (secs: number) => {
    const m = Math.floor(secs / 60).toString().padStart(2, "0");
    const s = (secs % 60).toString().padStart(2, "0");
    return `${m}:${s}`;
  };

  useEffect(() => {
    return () => {
      if (recognitionRef.current) {
        recognitionRef.current.stop();
      }
    };
  }, []);

  const handleFiles = (files: FileList | null) => {
    if (files && files[0]) setFile(files[0]);
  };

  const onDrop = useCallback((e: React.DragEvent) => {
    e.preventDefault();
    setDragOver(false);
    handleFiles(e.dataTransfer.files);
  }, []);

  const startRecording = () => {
    setRecordingError(null);
    const SpeechRecognition = (window as any).SpeechRecognition || (window as any).webkitSpeechRecognition;

    if (!SpeechRecognition) {
      setRecordingError("Voice transcription isn't supported in this browser. Please use Google Chrome or Microsoft Edge.");
      return;
    }

    try {
      const recognition = new SpeechRecognition();
      recognition.continuous = true;
      recognition.interimResults = true;
      
      // Auto-detect browser language preference, or map to Urdu if selected
      recognition.lang = language === "ur" ? "ur-PK" : "en-US";

      recognition.onresult = (event: any) => {
        let finalTranscript = "";
        for (let i = event.resultIndex; i < event.results.length; ++i) {
          if (event.results[i].isFinal) {
            finalTranscript += event.results[i][0].transcript;
          }
        }
        if (finalTranscript) {
          setDescription((prev) => prev + (prev ? " " : "") + finalTranscript);
        }
      };

      recognition.onerror = (event: any) => {
        console.error("Speech recognition error:", event.error);
        if (event.error === "not-allowed") {
          setRecordingError("Microphone access was denied. Please allow microphone permissions.");
        } else {
          setRecordingError(`Transcription Error: ${event.error}`);
        }
        stopRecording();
      };

      recognition.onend = () => {
        setIsRecording(false);
      };

      recognitionRef.current = recognition;
      recognition.start();
      setIsRecording(true);
    } catch (err: any) {
      setRecordingError("Failed to start voice transcription.");
      setIsRecording(false);
    }
  };

  const stopRecording = () => {
    if (recognitionRef.current) {
      recognitionRef.current.stop();
      recognitionRef.current = null;
    }
    setIsRecording(false);
  };

  const toggleRecording = () => {
    if (isRecording) {
      stopRecording();
    } else {
      startRecording();
    }
  };

  const clearRecording = () => {
    stopRecording();
    setRecordingError(null);
  };

  const copyToClipboard = () => {
    if (!response) return;
    const sourcesText = response.sources.map(s => `- ${s.file} (Page ${s.page})`).join("\n");
    const text = `
HAQAI LEGAL BRIEF
${response.response}

Sources Cited:
${sourcesText}

Accuracy Confidence: ${response.metrics.average_accuracy}%
Total Latency: ${response.metrics.total_latency}s
    `.trim();
    navigator.clipboard.writeText(text);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const submit = async () => {
    if (!description.trim() && !file && !audioBlob) return;
    setLoading(true);
    setResponse(null);
    setScanStep(0);

    // Parallel API call
    const apiPromise = (async () => {
      let url = "http://127.0.0.1:8000/query";
      let options: RequestInit = {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ query: description }),
      };

      if (file) {
        url = "http://127.0.0.1:8000/upload-image";
        const formData = new FormData();
        formData.append("file", file);
        options = {
          method: "POST",
          body: formData,
        };
      }

      const res = await fetch(url, options);
      if (!res.ok) {
        throw new Error("Failed to connect to HaqAI legal processor.");
      }
      return res.json();
    })();

    const steps = [
      "Extracting OCR text & documents...",
      "Analyzing Pakistan Penal Code (PPC) and Civil Codes...",
      "Cross-referencing Supreme Appellate Precedents...",
      "Synthesizing legal counsel brief...",
    ];

    try {
      for (let i = 0; i < steps.length; i++) {
        setScanStep(i);
        await new Promise((r) => setTimeout(r, 600));
      }

      const data = await apiPromise;
      setResponse(data);
      setFile(null);          // Clear file state so subsequent queries don't resend the same file
      setDescription("");     // Clear description field for next query
    } catch (err: any) {
      console.error(err);
      alert(err.message || "An error occurred while connecting to the backend.");
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className="min-h-screen bg-background text-foreground relative">
      <Navbar />

      <main className="pt-28 pb-20 px-6 lg:px-10 max-w-7xl mx-auto relative z-10">
        
        {/* Header Section */}
        <div className="mb-10 flex flex-col md:flex-row md:items-end md:justify-between gap-6">
          <div>
            <div className="inline-flex items-center gap-2 px-3 py-1 rounded-full border border-gold/30 bg-gold/5 text-gold text-xs uppercase tracking-[0.25em] mb-4">
              <Sparkles className="w-3.5 h-3.5" />
              {translations[language].portalBadge}
            </div>
            <h1 className="font-display text-4xl md:text-6xl font-semibold tracking-tight">
              {translations[language].title} <span className="text-gradient-gold">{translations[language].desk}</span>
            </h1>
            <p className="text-muted-foreground max-w-2xl mt-2 leading-relaxed">
              {translations[language].subtitle}
            </p>
          </div>
        </div>

        {/* Console Layout Grid */}
        <div className="grid lg:grid-cols-12 gap-8 items-start">
          
          {/* LEFT PANEL: CASE INPUT */}
          <div className="lg:col-span-6 rounded-xl border border-border bg-card/65 backdrop-blur-xl p-6 md:p-8 shadow-elegant flex flex-col relative overflow-hidden">
            
            {/* Ambient accent inside card */}
            <div className="absolute top-0 right-0 w-32 h-32 bg-gold/5 rounded-full blur-2xl pointer-events-none" />

            <div className="flex items-center justify-between mb-6 border-b border-border/50 pb-4">
              <h2 className="font-display text-2xl flex items-center gap-3">
                <FileText className="w-5 h-5 text-gold" />
                {translations[language].caseSubmissions}
              </h2>
              <span className="text-[10px] tracking-wider text-muted-foreground uppercase flex items-center gap-1.5">
                <Activity className="w-3.5 h-3.5 text-gold animate-pulse" />
                {translations[language].liveAnalysisNode}
              </span>
            </div>

            {/* Document Uploader */}
            <div className="space-y-2">
              <label className="text-xs font-medium uppercase tracking-[0.2em] text-gold/80 block">
                {translations[language].attachFiles}
              </label>
              <div
                onDragOver={(e) => {
                  e.preventDefault();
                  setDragOver(true);
                }}
                onDragLeave={() => setDragOver(false)}
                onDrop={onDrop}
                onClick={() => fileInput.current?.click()}
                className={`relative cursor-pointer rounded-xl border-2 border-dashed transition-all duration-300 p-8 text-center flex flex-col items-center justify-center min-h-[140px] ${
                  dragOver
                    ? "border-gold bg-gold/10 shadow-gold"
                    : "border-border hover:border-gold/50 hover:bg-secondary/40"
                }`}
              >
                <input
                  ref={fileInput}
                  type="file"
                  accept="application/pdf,image/*"
                  className="hidden"
                  onChange={(e) => handleFiles(e.target.files)}
                />

                {/* Simulated scan laser line during loading */}
                {loading && (
                  <div className="absolute inset-x-0 h-0.5 bg-gradient-to-r from-transparent via-gold to-transparent animate-[bounce_2s_infinite] top-0 pointer-events-none" />
                )}

                {file ? (
                  <div className="flex items-center justify-between w-full gap-4 text-left">
                    <div className="flex items-center gap-3 min-w-0">
                      <div className="w-12 h-12 rounded-lg bg-gold/10 border border-gold/30 flex items-center justify-center shrink-0">
                        <FileText className="w-5 h-5 text-gold" />
                      </div>
                      <div className="min-w-0">
                        <div className="text-sm font-medium truncate text-foreground">{file.name}</div>
                        <div className="text-xs text-muted-foreground">
                          {(file.size / 1024).toFixed(1)} KB
                        </div>
                      </div>
                    </div>
                    <button
                      onClick={(e) => {
                        e.stopPropagation();
                        setFile(null);
                      }}
                      className="p-2 rounded-lg bg-secondary/50 hover:bg-destructive/20 text-muted-foreground hover:text-destructive transition-colors"
                    >
                      <X className="w-4 h-4" />
                    </button>
                  </div>
                ) : (
                  <>
                    <div className="w-12 h-12 rounded-full bg-gold/10 border border-gold/30 flex items-center justify-center mb-3 group-hover:scale-105 transition-transform">
                      <Upload className="w-5 h-5 text-gold" />
                    </div>
                    <div className="text-sm font-medium">{translations[language].dragDrop}</div>
                    <div className="text-xs text-muted-foreground mt-1">
                      {translations[language].fileTypes}
                    </div>
                  </>
                )}
              </div>
            </div>

            {/* Description Textarea / Recording Overlay */}
            <div className="mt-6 space-y-2">
              <div className="flex items-center justify-between">
                <label className="text-xs font-medium uppercase tracking-[0.2em] text-gold/80">
                  {translations[language].provideFacts}
                </label>
              </div>
              
              <div className="relative rounded-xl overflow-hidden border border-border bg-background/30">
                {/* Text Input Area */}
                <textarea
                  value={description}
                  onChange={(e) => setDescription(e.target.value)}
                  rows={6}
                  placeholder={translations[language].placeholderText}
                  className={`w-full bg-transparent outline-none p-4 pr-14 pb-16 text-sm resize-none transition-all duration-300 leading-relaxed ${
                    language === "ur" ? "text-right font-display" : "text-left"
                  }`}
                  dir={language === "ur" ? "rtl" : "ltr"}
                />

                {/* 3D Holographic Voice Recorder Overlay */}
                <AnimatePresence>
                  {isRecording && (
                    <motion.div
                      initial={{ opacity: 0, scale: 0.96 }}
                      animate={{ opacity: 1, scale: 1 }}
                      exit={{ opacity: 0, scale: 0.96 }}
                      className="absolute inset-0 bg-slate-950/95 backdrop-blur-md z-20 flex flex-col items-center justify-center p-6"
                    >
                      {/* Holographic 3D Rotating Rings */}
                      <div className="relative w-32 h-32 flex items-center justify-center mb-4">
                        {/* Ring 1 (tilted & rotating) */}
                        <div 
                          className="absolute w-28 h-28 rounded-full border border-gold/40 animate-[spin_5s_linear_infinite]"
                          style={{ transform: "rotateX(60deg) rotateY(15deg)" }}
                        />
                        {/* Ring 2 (tilted & counter-rotating) */}
                        <div 
                          className="absolute w-32 h-32 rounded-full border-2 border-dashed border-gold/20 animate-[spin_9s_linear_infinite_reverse]"
                          style={{ transform: "rotateX(60deg) rotateY(-15deg)" }}
                        />
                        {/* Core pulsing glowing orb */}
                        <div className="w-16 h-16 rounded-full bg-gradient-to-tr from-gold to-gold-soft flex items-center justify-center shadow-[0_0_30px_rgba(201,168,76,0.5)] animate-pulse z-10 border border-gold/50">
                          <Mic className="w-6 h-6 text-[var(--navy-deep)] animate-bounce" />
                        </div>
                      </div>

                      <div className="text-xs uppercase tracking-[0.25em] text-gold font-bold mb-1">
                        {translations[language].audioNode}
                      </div>
                      
                      <div className="text-2xl font-mono font-semibold text-white tracking-widest mb-4">
                        {formatTime(recordingSeconds)}
                      </div>

                      {/* Engaging Frequency Visualizer */}
                      <div className="flex items-end gap-1 h-12 px-6">
                        {Array.from({ length: 24 }).map((_, i) => {
                          const duration = 0.5 + Math.random() * 0.7;
                          const delay = Math.random() * 0.6;
                          return (
                            <div
                              key={i}
                              className="w-1 h-10 bg-gradient-to-t from-gold to-gold-soft rounded-full audio-pulse-bar"
                              style={{
                                animationDuration: `${duration}s`,
                                animationDelay: `${delay}s`,
                              }}
                            />
                          );
                        })}
                      </div>
                    </motion.div>
                  )}
                </AnimatePresence>

                {/* Form Controls Bar (Inside Textarea box bottom) */}
                <div className={`absolute bottom-3 left-3 right-3 flex items-center justify-between border-t border-border/40 pt-3 z-30 ${
                  language === "ur" ? "flex-row-reverse" : "flex-row"
                }`}>
                  <div className="flex items-center gap-2">
                    {!isRecording && audioUrl ? (
                      <div className="flex items-center gap-2 bg-secondary/80 px-2.5 py-1 rounded-lg border border-border">
                        <Volume2 className="w-3.5 h-3.5 text-gold" />
                        <audio src={audioUrl} controls className="w-32 h-6 scale-90" />
                        <button
                          type="button"
                          onClick={clearRecording}
                          className="text-muted-foreground hover:text-destructive transition-colors"
                        >
                          <X className="w-3.5 h-3.5" />
                        </button>
                      </div>
                    ) : !isRecording && (
                      <span className="text-xs text-muted-foreground">{translations[language].voiceAnnotationInactive}</span>
                    )}
                  </div>

                  <button
                    type="button"
                    onClick={toggleRecording}
                    className={`p-3 rounded-xl border transition-all duration-300 flex items-center justify-center shadow-lg
                      ${
                        isRecording
                          ? "border-destructive bg-destructive text-white shadow-destructive/20 scale-105 active:scale-95"
                          : "border-border bg-gradient-to-b from-secondary/80 to-secondary text-muted-foreground hover:text-gold hover:border-gold/50 shadow-black/30 hover:shadow-gold/15 hover:translate-y-[-1px] active:translate-y-[1px]"
                      }`}
                  >
                    {isRecording ? <Square className="w-4 h-4" /> : <Mic className="w-4 h-4" />}
                  </button>
                </div>
              </div>
              {recordingError && (
                <p className="text-xs text-destructive">{recordingError}</p>
              )}
            </div>

            {/* Submission Button */}
            <button
              onClick={submit}
              disabled={loading || (!description.trim() && !file && !audioBlob)}
              className="mt-6 w-full group relative inline-flex items-center justify-center gap-2.5 px-6 py-4 rounded-xl font-bold shadow-gold overflow-hidden transition-all duration-300 disabled:shadow-none disabled:cursor-not-allowed
                enabled:bg-gradient-to-r enabled:from-[oklch(0.85_0.12_88)] enabled:to-[oklch(0.72_0.14_80)] enabled:text-[var(--navy-deep)] enabled:hover:scale-[1.01] enabled:active:scale-[0.99]
                disabled:bg-secondary/30 disabled:border disabled:border-border/60 disabled:text-muted-foreground/40"
            >
              {loading ? (
                <>
                  <Loader2 className="w-4 h-4 animate-spin text-[var(--navy-deep)]" />
                  {translations[language].submitLoading}
                </>
              ) : (
                <>
                  <Send className="w-4 h-4 transition-transform group-hover:translate-x-1 group-hover:-translate-y-0.5" />
                  {translations[language].submitBtn}
                </>
              )}
            </button>
            
            <div className="mt-4 flex items-center gap-2 text-xs text-muted-foreground bg-secondary/20 p-2.5 rounded-lg border border-border/40">
              <ShieldCheck className="w-4 h-4 text-gold shrink-0" />
              <span>{translations[language].encryptionAlert}</span>
            </div>
          </div>

          {/* RIGHT PANEL: OUTPUT BRIEFING */}
          <div className="lg:col-span-6 rounded-xl border border-border bg-card/65 backdrop-blur-xl p-6 md:p-8 shadow-elegant min-h-[550px] flex flex-col relative overflow-hidden">
            
            {/* Ambient accent inside card */}
            <div className="absolute bottom-0 left-0 w-32 h-32 bg-primary/5 rounded-full blur-2xl pointer-events-none" />

            <div className="flex items-center justify-between mb-6 border-b border-border/50 pb-4">
              <h2 className="font-display text-2xl flex items-center gap-3">
                <Scale className="w-5 h-5 text-gold" />
                {translations[language].briefTitle}
              </h2>

              {response && (
                <div className="flex items-center gap-2">
                  <button
                    onClick={copyToClipboard}
                    className="p-2 rounded-lg bg-secondary/60 hover:bg-secondary border border-border text-muted-foreground hover:text-foreground transition-all flex items-center gap-1.5 text-xs"
                    title={language === "en" ? "Copy brief" : "کاپی کریں"}
                  >
                    {copied ? (
                      <>
                        <Check className="w-3.5 h-3.5 text-green-500" />
                        {translations[language].copiedBtn}
                      </>
                    ) : (
                      <>
                        <Copy className="w-3.5 h-3.5" />
                        {translations[language].copyBtn}
                      </>
                    )}
                  </button>
                  <button
                    className="p-2 rounded-lg bg-secondary/60 hover:bg-secondary border border-border text-muted-foreground hover:text-foreground transition-all"
                    title={language === "en" ? "Export PDF" : "پی ڈی ایف ایکسپورٹ"}
                  >
                    <FileDown className="w-3.5 h-3.5" />
                  </button>
                </div>
              )}
            </div>

            <div className="flex-1 flex flex-col justify-center">
              <AnimatePresence mode="wait">
                
                {/* 1. Loading Step Progression */}
                {loading ? (
                  <motion.div
                    key="loading"
                    initial={{ opacity: 0, scale: 0.98 }}
                    animate={{ opacity: 1, scale: 1 }}
                    exit={{ opacity: 0, scale: 0.98 }}
                    className="flex flex-col items-center justify-center text-center py-10"
                  >
                    <div className="relative w-20 h-20 mb-8">
                      <div className="absolute inset-0 rounded-full border-2 border-gold/15" />
                      <div className="absolute inset-0 rounded-full border-2 border-transparent border-t-gold animate-spin" />
                      <Gavel className="absolute inset-0 m-auto w-8 h-8 text-gold animate-bounce" />
                    </div>
                    
                    <h3 className="font-display text-2xl mb-4 text-gradient-gold font-semibold">
                      {language === "en" ? "Legal Intelligence Processing" : "قانونی معلومات کی پروسیسنگ"}
                    </h3>
                    
                    {/* Simulated process timeline */}
                    <div className="w-full max-w-xs bg-secondary/50 rounded-full h-1 overflow-hidden mb-6">
                      <div 
                        className="bg-gold h-full transition-all duration-500" 
                        style={{ width: `${(scanStep + 1) * 25}%` }} 
                      />
                    </div>

                    <div className="space-y-2 text-sm text-muted-foreground w-full max-w-sm">
                      {(language === "en" ? [
                        "Extracting OCR text & documents...",
                        "Analyzing Pakistan Penal Code (PPC) and Civil Codes...",
                        "Cross-referencing Supreme Appellate Precedents...",
                        "Synthesizing legal counsel brief...",
                      ] : [
                        "دستاویزات اور تحریر اخذ کی جا رہی ہے...",
                        "تعزیرات پاکستان اور دیوانی قوانین کا تجزیہ کیا جا رہا ہے...",
                        "اعلیٰ عدالتوں کے فیصلوں کا موازنہ کیا جا رہا ہے...",
                        "قانونی رائے تیار کی جا رہی ہے...",
                      ]).map((step, idx) => (
                        <div 
                          key={step} 
                          className={`flex items-center justify-center gap-2.5 transition-opacity duration-300 ${
                            idx === scanStep 
                              ? "text-gold font-medium opacity-100" 
                              : idx < scanStep 
                              ? "text-muted-foreground opacity-60" 
                              : "opacity-30"
                          }`}
                        >
                          <span className={`w-1.5 h-1.5 rounded-full ${
                            idx <= scanStep ? "bg-gold" : "bg-muted"
                          }`} />
                          {step}
                        </div>
                      ))}
                    </div>
                  </motion.div>
                ) : response ? (
                  
                  // 2. Beautiful Structured Legal Brief Output
                  <motion.div
                    key="response"
                    initial={{ opacity: 0, y: 12 }}
                    animate={{ opacity: 1, y: 0 }}
                    exit={{ opacity: 0 }}
                    transition={{ duration: 0.6, ease: "easeOut" }}
                    className="space-y-6"
                  >
                    {/* Legal Brief Header */}
                    <div className="flex items-center justify-between border-b border-border/40 pb-4">
                      <div className="flex items-center gap-2">
                        <div className="w-8 h-8 rounded-full bg-gold/15 flex items-center justify-center">
                          <Scale className="w-4 h-4 text-gold" />
                        </div>
                        <span className="text-xs font-semibold uppercase tracking-widest text-gold">
                          {language === "en" ? "HaqAI Advisor Output" : "HaqAI ایڈوائزر آؤٹ پٹ"}
                        </span>
                      </div>
                      <span className="text-[10px] bg-red-950/40 text-red-400 border border-red-900/35 px-2.5 py-0.5 rounded font-mono">
                        {language === "en" ? "PRIVILEGED & CONFIDENTIAL" : "خصوصی اور خفیہ"}
                      </span>
                    </div>

                    {/* Live Performance & Accuracy Dashboard */}
                    <div className="bg-secondary/40 border border-border/60 rounded-xl p-4 space-y-3 shadow-inner">
                      <div className="flex items-center justify-between border-b border-border/40 pb-2">
                        <span className="text-xs font-bold uppercase tracking-wider text-gold flex items-center gap-1.5">
                          <Activity className="w-3.5 h-3.5 animate-pulse text-gold" />
                          {translations[language].metricsTitle}
                        </span>
                      </div>
                      <div className="grid grid-cols-2 gap-4">
                        <div className="bg-background/40 border border-border/30 rounded-lg p-3 text-center">
                          <div className="text-xs text-muted-foreground uppercase tracking-wider mb-1">{translations[language].retrievalAccuracy}</div>
                          <div className="text-2xl font-bold text-green-400">{response.metrics.average_accuracy}%</div>
                          <div className="text-[10px] text-muted-foreground mt-0.5">{translations[language].vectorMatch}</div>
                        </div>
                        <div className="bg-background/40 border border-border/30 rounded-lg p-3 text-center">
                          <div className="text-xs text-muted-foreground uppercase tracking-wider mb-1">{translations[language].processSpeed}</div>
                          <div className="text-2xl font-bold text-white">{response.metrics.total_latency}s</div>
                          <div className="text-[10px] text-muted-foreground mt-0.5">{translations[language].retrieval}: {response.metrics.retrieval_latency}s | {translations[language].generation}: {response.metrics.generation_latency}s</div>
                        </div>
                      </div>
                    </div>

                    {/* Section 1: Detailed Legal Analysis */}
                    <div className="space-y-2">
                      <div className="text-xs uppercase tracking-widest text-muted-foreground font-semibold flex items-center gap-2">
                        <span className="w-1.5 h-1.5 rounded-full bg-gold" />
                        {translations[language].analysisFindings}
                      </div>
                      <div className="bg-secondary/20 border border-border/30 rounded-xl p-5 text-sm leading-relaxed text-foreground/90 whitespace-pre-line font-sans" dir={language === "ur" ? "rtl" : "ltr"}>
                        {response.response}
                      </div>
                    </div>

                    {/* Section 2: Cited Local Documents / References */}
                    <div className="space-y-2">
                      <div className="text-xs uppercase tracking-widest text-muted-foreground font-semibold flex items-center gap-2">
                        <span className="w-1.5 h-1.5 rounded-full bg-gold" />
                        {translations[language].statutesPrecedents}
                      </div>
                      {response.sources.length === 0 ? (
                        <div className="text-sm text-muted-foreground bg-secondary/10 border border-border/20 rounded-lg p-3 italic">
                          {translations[language].noSources}
                        </div>
                      ) : (
                        <ul className="space-y-2">
                          {response.sources.map((src, i) => (
                            <li key={i} className="text-sm bg-secondary/20 border border-border/30 rounded-lg p-3 flex items-start gap-2.5">
                              <BookOpen className="w-4 h-4 text-gold shrink-0 mt-0.5" />
                              <span className="text-foreground/90">
                                <span className="font-semibold text-gold">{src.file}</span>
                                <span className="text-muted-foreground text-xs ml-2">({language === "en" ? "Page" : "صفحہ"} {src.page})</span>
                              </span>
                            </li>
                          ))}
                        </ul>
                      )}
                    </div>

                    {/* Divider & Disclaimer */}
                    <div className="border-t border-border/40 pt-4 mt-6">
                      <p className="text-[11px] text-muted-foreground/80 leading-relaxed italic">
                        {translations[language].disclaimer}
                      </p>
                    </div>
                  </motion.div>
                ) : (
                  
                  // 3. Placeholder Screen
                  <motion.div
                    key="placeholder"
                    initial={{ opacity: 0 }}
                    animate={{ opacity: 1 }}
                    exit={{ opacity: 0 }}
                    className="flex flex-col items-center justify-center text-center py-12"
                  >
                    <div className="w-16 h-16 rounded-full bg-gold/10 border border-gold/30 flex items-center justify-center mb-5 animate-pulse">
                      <Scale className="w-7 h-7 text-gold" />
                    </div>
                    <h3 className="font-display text-2xl mb-2 font-medium">
                      {translations[language].dispatchTitle}
                    </h3>
                    <p className="text-sm text-muted-foreground max-w-sm leading-relaxed">
                      {translations[language].dispatchSubtitle}
                    </p>
                    <div className="mt-6 inline-flex items-center gap-2 text-xs uppercase tracking-[0.2em] text-gold/60">
                      <span>{translations[language].waitingInputs}</span>
                      <ArrowRight className="w-3.5 h-3.5" />
                    </div>
                  </motion.div>
                )}
              </AnimatePresence>
            </div>
          </div>
        </div>
      </main>
    </div>
  );
}
